### ISSUE TITLE
The order of the all properties resolving should be changed

### ISSUE THREAD

**Issue by tux4ever** [porscheinformatik/zanata-spring#4]
At the moment the properties are loaded from zanata and overwritten from the parent message source. It would be better only to add missing properties and always take the values from zanata.

**Comment by romankh** [comment]
Yes, I think so too.
@derkoe: would you accept a pull request for that ?

**Comment by tux4ever** [comment]
The order has now changed. Only the properties that are not in zanata are added from the fallback message source.
